project_name: "test"
language: typescript
entry_points:
  - src/index.ts
ignored_dirs:
  - node_modules
  - .git
  - dist
  - coverage
  - __pycache__
  - .kiro
  - .claude
ignored_files:
  - "*.log"
  - "*.tmp"
  - ".env*"
  - "*.jpg"
  - "*.png"
  - "*.pdf"
  - "*.zip"
max_file_size: 1048576
show_logs: true
use_lsp: true

# セキュリティ設定
security:
  exclude_sensitive:
    - "**/*.key"
    - "**/*.pem"
    - "**/secrets/**"
  sanitize_logs: true
